name: CI

on:
  pull_request:
    branches:
      - master
      - development

jobs:
  test:
    name: Flutter Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "1.7.8+hotfix.4"
      - run: flutter doctor
      - run: flutter pub get
